### ISSUE TITLE
Wrong plane in plots

### ISSUE THREAD

**Issue by HuelsMat** [ssebastianmag/hydrogen-wavefunctions#1]
Hi,

thanks for this comprehensive illustration of the hydrogen orbitals!

There might be a typo in `line 120` of `hydrogen_wavefunction_annotated.py`. 
Instead of the $x-y$ plane you are plotting in the $z-x$ (or $z-y$, circular symmetry) if you stick to the standard convention of $z$ being the quantization axis. 

You can see this in `line 137`, where $\Theta = \arctan(x/y)$ only corresponds to the standard definition (https://en.wikipedia.org/wiki/Spherical_coordinate_system) of spherical coordinates if you replace $y$ by $z$. 

All the best,
Matthias

**Comment by ssebastianmag** [comment]
Hey, Matthias 

You're absolutely right about the $x-y$ and $z-x$ (or $z-y$) plane mix-up, the current setup wouldn't follow the standard spherical coordinate convention. If we indeed consider the $z$-axis as the axis of quantization then our grid would need to represent the $z-x$ or $z-y$ plane.

So... i've made some updates to align with such conventions properly: 

```
z = x = np.linspace(-grid_extent, grid_extent, grid_resolution)
z, x = np.meshgrid(z, x)
```
- Adjusted the theta calculation to make sure it's using the $z$-axis as the vertical in our $z-x$ plane setup.
- Updated the radial distance calculation to match our $z-x$ plotting plane, so it's now using the full 3D distance as it should. 

```
psi = radial_function(
        n, l, np.sqrt((x ** 2 + z ** 2)), a0
    ) * angular_function(
        m, l, np.arctan(x / (z + eps)), 0
    )
```
- Added a transpose on the array before plotting to align the calculated $z-x$ plane with matplotlib's $y-x$ imshow display
```
im = ax.imshow(np.sqrt(prob_density).T, cmap=sns.color_palette(colormap, as_cmap=True))
```

Let me know if I missed something and thanks a lot for pointing this out! 
It's super helpful to have an extra set of eyes on this stuff. 

Cheers,
Sebastian
